meta_product_name: "Mentor Hub"
meta_title: "Mentor Hub - Knowledge doesn't retire"
meta_description: "We match reitrees with recent graduates and young people seeking industry advice"
meta_image: "banner.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
